services:
  postgres:
    container_name: ultri-pg
    hostname: "postgres"
    command: ["postgres", "-c", "log_statement=all"]
    image: "postgres:14"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    restart: "no"
    env_file: ".env"
    networks:
      - ultri-net
    volumes:
      - "./docker-postgres/sql:/sql"
      - ultri-pg:/var/lib/postgres/data
      - ./docker-postgres:/docker-entrypoint-initdb.d/
volumes:
  ultri-pg: {}

networks:
  ultri-net:
    external: false
    driver: bridge
