#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER"  --dbname "$DB_NAME" <<-EOSQL
  BEGIN;
    CREATE USER $SUPERTOKENS_USER WITH PASSWORD '$SUPERTOKENS_PASS';
    GRANT CONNECT ON DATABASE $DB_NAME TO $SUPERTOKENS_USER;
    GRANT CREATE ON DATABASE $DB_NAME TO $SUPERTOKENS_USER;
    CREATE SCHEMA supertokens;
    GRANT USAGE ON SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    ALTER SCHEMA supertokens OWNER TO $SUPERTOKENS_USER;
    
  COMMIT;

EOSQL